
#include <unordered_map>

#include "item.h"

std::string GetItemFile(ItemID item)
{
    static auto ITEM_FILE_MAP = []()
    {
        std::unordered_map<ItemID, std::string> map {
            {ItemID::none, "none.png"},
            {ItemID::aluminum, "aluminum.png"},
            {ItemID::aluminum_ore, "aluminum_ore.png"},
            {ItemID::amethyst_ore, "amethyst_ore.png"},
            {ItemID::beryllium, "beryllium.png"},
            {ItemID::blue_crystal, "blue_crystal.png"},
            {ItemID::boron_crystal, "boron_crystal.png"},
            {ItemID::calcite, "calcite.png"},
            {ItemID::carbon, "carbon.png"},
            {ItemID::chalchanthite, "chalchanthite.png"},
            {ItemID::dirt, "dirt.png"},
            {ItemID::feldspar, "feldspar.png"},
            {ItemID::glass, "glass.png"},
            {ItemID::gold_ore, "gold_ore.png"},
            {ItemID::granite, "granite.png"},
            {ItemID::graphite, "graphite.png"},
            {ItemID::gravel, "gravel.png"},
            {ItemID::light, "light.png"},
            {ItemID::magnetite, "magnetite.png"},
            {ItemID::molybdenum_ore, "molybdenum_ore.png"},
            {ItemID::moon_bark, "moon_bark.png"},
            {ItemID::moon_leaf, "moon_leaf.png"},
            {ItemID::moon_wood, "moon_wood.png"},
            {ItemID::neptunium, "neptunium.png"},
            {ItemID::notchium, "notchium.png"},
            {ItemID::notchium_ore, "notchium_ore.png"},
            {ItemID::phosphate, "phosphate.png"},
            {ItemID::polymer, "polymer.png"},
            {ItemID::quartz_ore, "quartz_ore.png"},
            {ItemID::rock, "rock.png"},
            {ItemID::sand, "sand.png"},
            {ItemID::shale_gravel, "shale_gravel.png"},
            {ItemID::silver_ore, "silver_ore.png"},
            {ItemID::snow, "snow.png"},
            {ItemID::sulphur_crystal, "sulphur_crystal.png"},
            {ItemID::sulphur_ore, "sulphur_ore.png"},
            {ItemID::titanium, "titanium.png"},
            {ItemID::titanium_ore, "titanium_ore.png"},
            {ItemID::topsoil, "topsoil.png"},
            {ItemID::water, "water.png"},
            {ItemID::xenostone, "xenostone.png"},
            {ItemID::zircon_ore, "zircon_ore.png"},
            {ItemID::beacon, "beacon.png"},
            {ItemID::mechanism, "mechanism.png"},
            {ItemID::battery, "battery.png"},
            {ItemID::energy_orb, "energy_orb.png"},
            {ItemID::power_crystal, "power_crystal.png"},
            {ItemID::adhesive, "adhesive.png"},
            {ItemID::minilight, "minilight.png"},
            {ItemID::magnet, "magnet.png"},
            {ItemID::biogel, "biogel.png"},
            {ItemID::gold, "gold.png"},
            {ItemID::turret_t1, "turret_t1.png"},
            {ItemID::turret_t2, "turret_t2.png"},
            {ItemID::turret_t3, "turret_t3.png"},
            {ItemID::green_mob_egg, "green_mob_egg.png"},
            {ItemID::brown_mob_egg, "brown_mob_egg.png"},
            {ItemID::space_giraffe_egg, "space_giraffe_egg.png"},
            {ItemID::blue_i_egg, "blue_i_egg.png"},
            {ItemID::astronaut_egg, "astronaut_egg.png"},
            {ItemID::camera, "camera.png"},
            {ItemID::disk, "disk.png"},
            {ItemID::disk1, "disk.png"},
            {ItemID::disk2, "disk.png"},
            {ItemID::disk3, "disk.png"},
            {ItemID::disk4, "disk.png"},
            {ItemID::disk5, "disk.png"},
            {ItemID::disk6, "disk.png"},
            {ItemID::disk7, "disk.png"},
            {ItemID::disk8, "disk.png"},
            {ItemID::disk9, "disk.png"},
            {ItemID::disk10, "disk.png"},
            {ItemID::disk11, "disk.png"},
            {ItemID::disk12, "disk.png"},
            {ItemID::disk13, "disk.png"},
            {ItemID::disk14, "disk.png"},
            {ItemID::disk15, "disk.png"},
            {ItemID::disk16, "disk.png"},
            {ItemID::disk17, "disk.png"},
            {ItemID::disk18, "disk.png"},
            {ItemID::drill_t1, "drill_t1.png"},
            {ItemID::drill_t2, "drill_t2.png"},
            {ItemID::drill_t3, "drill_t3.png"},
            {ItemID::jetpack_t1, "jetpack_t1.png"},
            {ItemID::jetpack_t2, "jetpack_t2.png"},
            {ItemID::jetpack_t3, "jetpack_t3.png"},
            {ItemID::medkit, "medkit.png"},
            {ItemID::slug_pistol_t1, "slug_pistol_t1.png"},
            {ItemID::slug_pistol_t2, "slug_pistol_t2.png"},
            {ItemID::slug_pistol_t3, "slug_pistol_t3.png"},
            {ItemID::chronobooster, "chronobooster.png"},
            {ItemID::chronowinder, "chronowinder.png"}
        };

        return map;
    }();

    return ITEM_FILE_MAP[item];
}
